In [212]:
import numpy as np
import pandas as pd

In [213]:
dic = pd.read_pickle("data_batch_1")

In [214]:
KEYS = list(dic.keys())

In [215]:
X_train = list(dic[b'data'])
y = list(dic[b'labels'])

In [216]:
X_train = np.array(X_train , dtype = np.float128).reshape(10000,1024)
y_train = []

In [217]:
for i in y:
    temp = [0 for _ in range(10)]
    temp[i] = 1
    y_train.append(temp)

In [218]:
y_train = np.array(y_train,dtype = np.float128).reshape(10000,10)

In [219]:
X_train[0,:]

array([ 61.,  44.,  48., ..., 188., 124.,  99.], dtype=float128)

In [220]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_der(x):
    return sigmoid(x) *(1-sigmoid (x))
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

In [221]:
def compute_cost():
    return 0

In [222]:
def forward_prop(x,wh,wo,bh,bo):
    zh = np.dot(wh.T,x) + bh
##  2x1 = 2x1024 X 1024x1
    H = sigmoid(zh)
    
    
    zo = np.dot(wo.T,H) + bo
##  10x1  = 10x2 x 2x1

    yhat = sigmoid(zo)
##  10x1
    cache = {
        "zh":zh,
        "H":H,
        "zo":zo
    }
    return yhat , cache

In [223]:
def backward_prop(x,y,wh,wo,lr):
    yhat , cache = forward_prop(x,wh,wo,bh,bo)
##  10x1
    H = cache['H']
##  2x1   
    eo = yhat-y
##  10x1 = 10x1 - 10x1    
    eh = wo @ eo
##  2x1 = 2x10 X 10x1   
    dwo = H @ eo.T
##  2x10 = 2x1 x 1x10  -->   eo = 10x1
    dwh = x @ eh.T
##  1024x2 = 1024x1 X 1x2 --> eh = 2x1
    return dwh,dwo

In [224]:
def gradientDescent(dwh, dwo , alpha , iters , wh, wo):
    for i in range(iters):
        wh -= alpha*dwh
        wo -= alpha*dwo
    return wh,wo

In [225]:
i = -1
X = X_train[i,:].reshape(1024,1)
y = y_train[i,:].reshape(10,1)

wh = np.random.randn(1024,2) 
wo = np.random.randn(2,10) 
bh = np.full((2,1),0.1)
bo = np.full((10,1),0.1)

alpha = 0.3
iters = 100000

y_hat , cache = forward_prop (X , wh , wo , bh , bo)
dwh,dwo = backward_prop(X,y,wh,wo,alpha)
wh,wo = gradientDescent(dwh, dwo , alpha, iters , wh , wo)

##Final

ans , CACHE = forward_prop(X,wh,wo,bh,bo)
print(ans) 
print(y)

[[0.52497919]
 [0.52497919]
 [0.52497919]
 [0.52497919]
 [0.52497919]
 [0.52497919]
 [0.52497919]
 [0.52497919]
 [0.52497919]
 [0.52497919]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]]


/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
